---
 
 - hosts: all
   become: true
   pre_tasks:

   - name: install updates (amazon)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "Amazon"
   
   - name: install updates (ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

 
 - hosts: workstations
   become: true
   tasks:
   
   - name: install unzip 
     package: 
       name: unzip

   - name: install terraform
     unarchive: 
       src: https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_darwin_amd64.zip
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       owner: root
       group: root




 - hosts: web_servers
   become: true
   tasks:

   - name: install apache and php for Ubuntu servers
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"
 
   - name: install apache and php for Amazon servers
     tags: apache,amazon,httpd
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "Amazon"


   - name: start httpd (for amazon linux)
     tags: amazon, httpd, apache
     service: 
       name: httpd
       state: started
       enabled: yes
     when: ansible_distribution == "Amazon" 

   - name: start httpd (for ubuntu)
     tags: ubuntu,apache
     service: 
       name: apache2
       state: started
       enabled: yes
     when: ansible_distribution == "Ubuntu" 

   
   - name: change admin email
     tags: amazon,httpd,apache
     lineinfile: 
       path: /etc/httpd/conf/httpd.conf
       regexp: '^ServerAdmin'
       line: ServerAdmin newemailaddress.gmail.com
     when: ansible_distribution == "Amazon"
      
     

   - name: copy default html file for site
     tags: apache,apache2,httpd
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644



 - hosts: db_servers
   become: true
   tasks:

   - name: install mariadb package (Ubuntu)
     tags: ubuntu,db,mariadb
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"
 
   - name: install mariadb package (Amazon)
     tags: amazon,db,mariadb
     dnf:
       name: mariadb
       state: latest
     when: ansible_distribution == "Amazon"



 - hosts: file_servers
   become: true
   tasks:

   - name: install samba package
     tags: samba
     package:
       name: samba
       state: latest
   
