---
 
 - hosts: all
   become: true
   pre_tasks:

   - name: install updates (amazon)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "Amazon"
   
   - name: install updates (ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"




 - hosts: web_servers
   become: true
   tasks:

   - name: install apache and php for Ubuntu servers
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"
 
   - name: install apache and php for Amazon servers
     tags: apache,amazon,httpd
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "Amazon"




 - hosts: db_servers
   become: true
   tasks:

   - name: install mariadb package (Ubuntu)
     tags: ubuntu,db,mariadb
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"
 
   - name: install mariadb package (Amazon)
     tags: amazon,db,mariadb
     dnf:
       name: mariadb
       state: latest
     when: ansible_distribution == "Amazon"



 - hosts: file_servers
   become: true
   tasks:

   - name: install samba package
     tags: samba
     package:
       name: samba
       state: latest
   
